### ISSUE TITLE
Safari 9 style scope test failing with the latest webcomponentsjs polyfill

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-overlay#116]
The following test is failing on Safari 9 only (both in CI and iOS Simlulator locally):

```
iOS Simulator iphone 9.3 ✖ test/styling.html » overlay content styling » local styles property » should have overlay style scope on the content part
  expected 'x-scope [secure]-content-13-1' to include 'style-scope [secure]'
    <unknown> at   AssertionError at /components/chai/chai.js:5270:0
    <unknown> at           assert at /components/chai/chai.js:265:0
    <unknown> at          include at /components/chai/chai.js:567:0
    <unknown> at           assert at /components/chai/chai.js:3839:0
    <unknown> at        <unknown> at styling.html:322:0
```

Possibly related: webcomponents/webcomponentsjs#985

**Comment by web-padawan** [comment]
Closing as we no longer test in Safari 9 due to the fact that SauceLabs removed its support 🙈

**Comment by DiegoCardoso** [comment]
This is how orders in Bakery in Safari 9 look like now:

![image](https://user-images.githubusercontent.com/262432/59590679-46c1bd00-90f5-11e9-931b-fef9176b8ac9.png)

With the help from @platosha. we could make it work by adding `style-scope vaadin-dialog-overlay` to the class list of the `[part=content]` element.

I believe this  is still relevant, since Safari 9 is supported by V14 (as can be seen under [Mobile Browsers section here](https://github.com/vaadin/platform/releases/tag/14.0.0.beta3)).

**Comment by web-padawan** [comment]
Reopened and marked as bug. Will need to investigate.
